# Default values for ts4u-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

namespace: ms-production

limits:
  cpu: "500m"
  memory: "1Gi"

requests:
  cpu: "500m"
  memory: "1Gi"

host: www.highpaidjobs.us

image:
  name: highpaidjobs
  repository: ts4udocker/highpaidjobs
  tag: production-latest
  pullPolicy: IfNotPresent
imagePullSecrets:
  name: regcred
